import type { EffectDescriptor, ProjectState } from "@/types/domain"

export const emptyProject: ProjectState = {
  media_path: "",
  metadata_cache: {},
  in_point: 0,
  out_point: 0,
  segments: [],
  selected_preset: "Stream copy",
  effect_chain: [],
  output_settings: {
    container: "mp4",
    video_codec: "copy",
    audio_codec: "copy",
    crf: 18,
    preset: "medium",
    output_path: "output.mp4",
  },
  app_version: "0.2.0",
}

export const fallbackEffects: EffectDescriptor[] = [
  {
    effect_id: "vs.knlmeanscl",
    name: "KNLMeansCL Denoise",
    engine: "vapoursynth",
    category: "denoise",
    description: "OpenCL denoise pass for modern VapourSynth workflows.",
    recommended: true,
    install_status: "missing",
    cpu_gpu_notes: "OpenCL GPU preferred.",
    license_notes: "Manual install until redistribution terms are verified.",
    parameters: [
      {
        name: "strength",
        type: "float",
        default: 1.2,
        min: 0,
        max: 5,
        step: 0.1,
        label: "Strength",
        description: "Main denoise amount. Higher values clean more noise but can soften fine detail.",
      },
    ],
    defaults: { strength: 1.2 },
    script_template: "clip = core.knlm.KNLMeansCL(clip, d=1, a=2, s={strength})",
  },
  {
    effect_id: "vs.resize.bicubic",
    name: "Bicubic Resize",
    engine: "vapoursynth",
    category: "resize",
    description: "Built-in resize operation.",
    recommended: true,
    install_status: "installed",
    cpu_gpu_notes: "CPU, fast.",
    license_notes: "Available with VapourSynth core.",
    parameters: [
      {
        name: "width",
        type: "int",
        default: 1920,
        min: 16,
        max: 16384,
        step: 2,
        label: "Width",
        description: "Output frame width in pixels.",
        unit: "px",
      },
      {
        name: "height",
        type: "int",
        default: 1080,
        min: 16,
        max: 16384,
        step: 2,
        label: "Height",
        description: "Output frame height in pixels.",
        unit: "px",
      },
    ],
    defaults: { width: 1920, height: 1080 },
    script_template: "clip = core.resize.Bicubic(clip, width={width}, height={height})",
  },
  {
    effect_id: "avs.mctemporaldenoise",
    name: "MCTemporalDenoise",
    engine: "avisynth",
    category: "degrain",
    description: "Legacy AviSynth+ compatibility descriptor.",
    recommended: false,
    install_status: "manual",
    cpu_gpu_notes: "64-bit AviSynth+ first; 32-bit bridge is roadmap.",
    license_notes: "Mixed dependency licensing, manual install only.",
    parameters: [
      {
        name: "settings",
        type: "enum",
        default: "medium",
        options: ["low", "medium", "high"],
        label: "Preset",
        description: "Legacy preset controlling denoise aggressiveness.",
      },
    ],
    defaults: { settings: "medium" },
    script_template: "clip = MCTemporalDenoise(clip, settings='{settings}')",
  },
]
